server:
  port: 8080

spring:
  application:
    name: weather-service
  datasource:
    #    url: DB_URL
    #    username: DB_USERNAME
    #    password: DB_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

# Management endpoints can be accessed via /actuator/feature endpoint
management:
  endpoints:
    web:
      exposure:
        include: feature

# JUnit test cases are dependent on this key; Hence, keeping it as a dummy key
# Runtime key is provided by docker-compose.yml
openweathermap:
  api:
    key: DUMMY_KEY_FOR_JUNIT_TEST_CASES

springdoc:
  api-docs:
    path: /v3/api-docs
  show-actuator: true
