name: Postman Runner

on:
  workflow_run:
    workflows: ["Project Build"]
    types:
      - completed

jobs:
  postman:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker
        run: |
          docker compose up --build -d

      - name: Download Postman Collection and Environment
        working-directory: ./app
        run: |
          mkdir -p postman
          curl -O ./app/postman/weather-service.postman_collection.json https://raw.githubusercontent.com/BytePiston/weather-service/master/postman_collection/weather-service.postman_collection.json
          curl -O ./app/postman/weather-service-env.postman_environment.json https://raw.githubusercontent.com/BytePiston/weather-service/master/postman_collection/weather-service-env.postman_environment.json

      - name: Run Postman Collection using Newman
        working-directory: ./app
        run: |
          docker run -t ./app/postman/newman:ubuntu run postman/weather-service.postman_collection.json -e ./app/postman/weather-service-env.postman_environment.json
