#name: Security Code Analysis
#
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    types: [opened, synchronize, reopened]
#
#jobs:
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v2
#
#    - name: Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#        java-version: '17'
#        distribution: 'adopt'
#        cache: 'maven'
#
#    - name: Grant execute permission for mvn
#      run: chmod +x mvnw
#
#    - name: Run OWASP Dependency-Check
#      run: ./mvnw dependencyCheckAnalyze
