name: Security Code Analysis

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  security:
    name: Run SpotBugs with Find-Sec-Bugs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Run SpotBugs with Find-Sec-Bugs
        run: |
          wget https://github.com/spotbugs/spotbugs/releases/download/4.5.3/spotbugs-4.5.3.tgz
          tar xzf spotbugs-4.5.3.tgz
          wget https://github.com/find-sec-bugs/find-sec-bugs/releases/download/version-1.11.0/findsecbugs-plugin-1.11.0.jar
          ./spotbugs-4.5.3/bin/spotbugs -pluginList findsecbugs-plugin-1.11.0.jar -textui -effort:max -threshold:Low -xml:withMessages -sortByClass -output spotbugs.xml .
